### ISSUE TITLE
Extend documentation of how to review PR of other contributors

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#105]
The current documentation missing the explanation how to review PRs from other contributors to the project, only covers when contributors are working on the same origin.

**Comment by FedericoEsparza** [comment]
@javpet This is covered in the current open PR [Add 'How to Review a PR' documentation #103](https://github.com/AgileVentures/sfn-client/pull/103)

It's linked at the top, linking it to the very bottom of the doc file.

I haven't merged because I needed to update the screenshot.

Working on it now.

**Comment by FedericoEsparza** [comment]
Adding file for use in PR:
<img width="822" alt="Screen Shot 2019-03-17 at 12 21 21 PM" src="https://user-images.githubusercontent.com/11988089/54495511-522a0000-48dc-11e9-9c31-90f56af1105e.png">
`https://user-images.githubusercontent.com/11988089/54495511-522a0000-48dc-11e9-9c31-90f56af1105e.png`
