### ISSUE TITLE
Install cypress

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#111]
Install cypress

We want to start connecting the frontend and backend by carving an end to end traversal of the app, using the artists as a beachhead, and a BDD, outside-in approach.

```
yarn add cypress --dev
```

https://docs.cypress.io/guides/getting-started/installing-cypress.html#yarn-add

**Comment by aonomike** [comment]
This was helpful as well http://dev.topheman.com/cypress-io-advanced-setup/
