### ISSUE TITLE
Document first iteration Definition of Ready

### ISSUE THREAD

**Issue by yakryder** [AgileVentures/sfn-client#121]
In looking at some of the open issues, I'm realizing we don't have a picture of what information is needed in a ticket before that ticket can be worked.

I see DoR (and DoD for that matter) as non-negotiables for a healthy project and associated culture of development. 

If there's disagreement there, please comment below.

My first suggestion would be we pull in something pretty standard for starters and iterate from there.

Acceptance Criteria:

- [ ] The DoR document contains information that limits the scope of what tickets can be worked in a way that enforces greater clarity of requirements and Definition of Done.
- [ ] The DoR document clearly indicates that tickets are not to be worked until they meet DoR
- [ ] The DoR document includes information on what to do if a ticket you are reviewing has been worked before meeting DoR
- [ ] The DoR document is linked from the README

**Comment by aonomike** [comment]
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

@mattwr18 @FedericoEsparza we are trying to set up a template for DoR for issues following the link above. We are not able to since we have no rights to see the settings button for the project maybe?

**Comment by FedericoEsparza** [comment]
@aonomike I just elevated you, @javpet and @dhemmingson to Admin status, along with @lollypop27 @SherSpock @RachitKansal and @mattwr18 , so you should all have **Settings** visibility (power) for the repo. Don't abuse it! 😁
