### ISSUE TITLE
Refactor class component into functional component

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#145]
Refactor class component into functional component
## Expected Behavior
`src/components/Artist/ArtistPerformance/ArtistPerformance.js` should be a functional component

**Comment by yakryder** [comment]
@FedericoEsparza Can we please be careful with the use of the word and label `refactor`. I am seeing this word appearing up and down the stack on this project and I'm inclined to reach for the Inigo Montoya word meme.

The conventional definition of refactor is changing (and hopefully improving) code organization without changing behavior. I would argue that a change cannot alter a public API and be deemed a refactoring -- which this change does for ArtistPerformance. 

By a more permissive definition of the word, I still see no advantage calling this a refactoring over a conversion.

**Comment by FedericoEsparza** [comment]
@SherSpock Duly noted, and you’re completely correct! 

I’ll adjust my use of the word, especially since you took the time to passionately articulate your argument. 😁

Thanks for addressing the duplicate PRs, by the way! Very much appreciated.
