### ISSUE TITLE
Add icons to Supported Causes and Related Artists

### ISSUE THREAD

**Issue by dhemmingson** [AgileVentures/sfn-client#151]
## Expected Behavior

Add icons to Supported Causes and Related Artists list items on the Artist page.
![Screen Shot 2019-03-31 at 10 26 19 AM](https://user-images.githubusercontent.com/9334646/55286695-75a27f80-539f-11e9-866c-6db93a9a2ea5.png)

## Current Behavior

Currently there are no icons:
<img width="613" alt="no-icons" src="https://user-images.githubusercontent.com/2614417/56084533-c54e6580-5df9-11e9-969d-b93632644e3e.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by jmpainter** [comment]
Would it be ok to use Font Awesome for these icons?

**Comment by FedericoEsparza** [comment]
Yes, you can use https://github.com/FortAwesome/react-fontawesome
