### ISSUE TITLE
Add pagination component

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#179]
Research on the best ways to create a pagination component implemenntation that can be reused across the app.

## Expected result
- A recommendation on how to implement pagination for the sfn-client app

**Comment by yakryder** [comment]
@FedericoEsparza Can we get some clarity on this statement from #165 (bolding my emphasis):

_You can optionally add pagination within this ticket, or that can be a different one. **Please don't implement your own pagination component, a la websiteone-FE.**_

**Comment by FedericoEsparza** [comment]
Matt and Joseph spent a few weeks, seemingly, rolling their own react pagination component. I’d rather we learn from their struggle and use our time more effectively.

**Comment by yakryder** [comment]
Sounds reasonable. I'm inclined to agree based on that and my own penchant for not making reusable components unless you're either [unflinchingly honestly] certain of their utility or are already dealing with triplication of logic (or more) in your codebase

Open to counters. This ticket is definitely the place for them

**Comment by FedericoEsparza** [comment]
Yeah, some React Developer already is out there wanting to make his reusable pagination component, that they spent a lot of time making look nice and functional for us, more popular. Let’s reward that effort and help promote their work; saving us some time, at the same time. 🙂

**Comment by javpet** [comment]
In this mindset that you discuss guys, how about this component? https://www.npmjs.com/package/react-paginate

**Comment by yakryder** [comment]
@javpet I like it! Cursory Google revealed three results, and that had the most stars. 

Far from a foolproof way to pick a library, but I'm guessing y'all did more research than I did. 

If so, can we roughly outline the reasons we picked it here before we forget?

And, if not, it is just pagination 🙃
