### ISSUE TITLE
Performances design mockup

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#186]
We have design mockups for most of the pages, but we are still missing some. It would be great to have them all.

## Expected Behavior

We should have all mockups of the sing for need project, so collaborators can freely pick up elements based on their interest.

## Current Behavior

We don't have currently the mockup for performances. 

## Possible Solution

Design the mockup similarly in Balsamiq as the others, and add it to the README.MD file.

**Comment by aonomike** [comment]
I will go ahead close this as @RachitKansal already provided us with them. Thanks @RachitKansal
