### ISSUE TITLE
Add `ArtistBio` styling

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#19]
Add `ArtistBio` styling

Call it `ArtistBio.scss` 

You can add headline and paragraph elements, along with Lorem ipsum  to the `<ArtistBio>` component to help you out.

**Comment by javpet** [comment]
We're thinking about to mimic these styles here: https://dribbble.com/shots/3144986-Online-Music-Streaming-Service-Artist-Page/attachments/666587 using this lightweight library: http://tachyons.io

**Comment by FedericoEsparza** [comment]
@javpet Something like this would be great!

**Comment by javpet** [comment]
Fixes https://github.com/AgileVentures/sfn-client/pull/55
