### ISSUE TITLE
Add Zenhub badge to README

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#191]
As we moved from Waffle to Zenhub we're missing our good old banner from the top of the README.

## Expected Behavior

Add Zenhub banner to README to have a clear overview of the project & process of sing for needs.

## Current Behavior

We don't have currently the Zenhub banner.

## Possible Solution

Adding Zenhub banner on top of README file.

Took a round of exploration with @dhemmingson and @aonomike found some resources, but not the exact information we were looking for:
- https://shields.io/category/build
- https://www.zenhub.com/faq

**Comment by dhemmingson** [comment]
We haven't been able to find an out-of-the-box solution so far. So, if we want this, we may have to roll our own. We could copy the look and behavior of the old badge. Is it worth the trouble, though?

Old Waffle badge:

![waffle_badge_snapshot](https://user-images.githubusercontent.com/2614417/56890141-3e76cb00-6a3e-11e9-887f-f08a6fd56696.png)

**Comment by javpet** [comment]
I think the old badge was really nice overview, what do you say @FedericoEsparza should we close this issue then?
