### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#200]
Pull request templates help guide developers make better software, and a better software development experience.

They are obviously extremely useful for open source projects that get many contributions from outsiders, but they can also be very useful for internal projects where all contributors are insiders.

They codify and encourage good behavior, thoughtful code, and empathetic interactions with teammates.

They normalize and reinforce a workflow regardless of size, scope, or underlying technology used in a project.

And they provide consistency and familiarity that makes switching between multiple projects per day a little easier.

## Expected Behavior

A template for documenting pull requests is added to be displayed whenever one one is making a PR
## Current Behavior

There is no pull request tempate added
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by daumie** [comment]
@aonomike  since I have worked on this on the Backend application
You can assign me on this issue as I don't have the rights to.

**Comment by FedericoEsparza** [comment]
@daumie I've assigned you to this ticket and granted you (temporary? 🤔) admin rights.

**Comment by daumie** [comment]
@FedericoEsparza About the rights, I think you only had to add me as a collaborator so that I can assign issues to self.

**Comment by FedericoEsparza** [comment]
@daumie You were already a collaborator, Dominic. You should be able to self-assign to tickets.

For issues there is a template option in the settings, which require admin rights to be able to see. 

<img width="765" alt="Screenshot 2019-05-14 05 49 05" src="https://user-images.githubusercontent.com/11988089/57692324-1ecdce00-760c-11e9-8b74-d50ddbbd3554.png">


So I thought it was similar for PR templates, but there's no setting for PR templates.

You can, however, follow this guide: https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

I think you did something similar for the backend template, so I'm just posting the link for team reference.

**Comment by daumie** [comment]
Thanks for getting back to me on this @FedericoEsparza

**Comment by daumie** [comment]
I have a pull request for this @FedericoEsparza , you might want to have a look at it.
