### ISSUE TITLE
Make Contribution Instructions Clear

### ISSUE THREAD

**Issue by daumie** [AgileVentures/sfn-client#201]
## Expected Behavior

The README should provide clear contribution instructions

## Current Behavior

Instructions contained in the README can be arranged in a clearer way

## Possible Solution

Edit README to provide make instructions  on setting of the `upstream` remote in a clear manner.

## Steps to Reproduce (for bugs)

N/A

## Context

When  setting up the remote  upstream, I realized the instructions were not specified in a clear way.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):
N/A

**Comment by FedericoEsparza** [comment]
@daumie Thanks for creating this ticket, Dominic. That's really helpful.

Could you indicate where it got confusing?

**Comment by daumie** [comment]
@FedericoEsparza Currently the README instructions work but could be arranged in a better way.

**Comment by FedericoEsparza** [comment]
@daumie I'm open to that. I want new contributors to easily set up their remotes.

Rather than ask you for more specifics about how they are not clear or proposed instructions that might have the instructions arranged better, I'll just suggest that you put in a PR making them more clear, in your eyes.

How does that sound? 🙂

**Comment by javpet** [comment]
@FedericoEsparza or @daumie do you have a suggestion for us which parts of the documentation we should change to make it clearer? Otherwise we might need to close this ticket.

**Comment by FedericoEsparza** [comment]
@javpet If @daumie has no further input on the ticket, let's close it. Let's give him a last call opportunity to respond.

**Comment by javpet** [comment]
As we haven't heard back in 1 week from @daumie I'm closing the ticket now. Thank you guys!
