### ISSUE TITLE
Separate pagination component

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#205]
Ryder had a great suggestion to separate the pagination to its own component, instead of importing the library into every instance of pagination.

## Expected Behavior

Pagination component is re-factored to its own component and the React-pagination library is imported into that.

## Current Behavior

Currently the pagination is handled // planned by individual imports from the React-pagination library

**Comment by yakryder** [comment]
😅 It's your suggestion! I agree it's a good one :)
