### ISSUE TITLE
Add Causes Carousel

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#208]
On the `cause/:id` page, add a Carousel that displays images about the cause. 
## Expected Behavior

A slide show with images about the Cause. See image below 
<img width="565" alt="Screen Shot 2019-05-05 at 8 21 23 PM" src="https://user-images.githubusercontent.com/1543546/57197725-6f418d80-6f73-11e9-8cae-c24f25af96ee.png">

## Current Behavior

The CauseImages carousel component has not been created yet
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by yakryder** [comment]
A simple request -- under no circumstances is this carousel to auto-advance. I am happy to provide supporting arguments if there are opinions to the contrary

**Comment by javpet** [comment]
Agreed @SherSpock! I think the best to manage only by the arrows.
