### ISSUE TITLE
Add Explore These Causes component to Causes index page

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#225]
The Causes index page currently not so filled with content, let's start building up by adding the components from the mockup.

<img width="732" alt="Screen Shot 2019-05-11 at 2 50 33 PM" src="https://user-images.githubusercontent.com/9334646/57569906-43535b80-73fc-11e9-86ea-6e5f50596c57.png">

## Expected Behavior

Explore these causes component added to the Causes container

## Current Behavior

Currently nothing has been added yet to the Causes index page.

**Comment by yakryder** [comment]
One native English speaker's opinion: 'Explore these Causes" or "Explore these causes", not a variant where "these" is capitalized

Additionally, "Humanitarian" does not appear to me to be a clear categorizer of causes. The planet icon (which many if not most users will expect to be for environment) makes it even less clear

**Comment by javpet** [comment]
Thanks again, it's always good to have a native speaker around! :) We're using FontAwesome icons currently, so these icons from the mockup are kind of placeholders, and we'll cook with what we have. 

Later in the project it's recommended to have our own icons of course.

**Comment by yakryder** [comment]
@javpet Makes sense!

How about [this one](https://fontawesome.com/icons/hands-helping?style=solid) (not pro-specific) or a [related one](https://fontawesome.com/icons?d=gallery&q=hand) for humanitarian

**Comment by javpet** [comment]
Thanks for the suggestions @SherSpock, I'll pick up this ticket today and experiment with these
