### ISSUE TITLE
Add sign up section to Causes index page

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#226]
Similarly as we have a sign up on the artists index page, we need a sign up on the Causes index page as well.

<img width="710" alt="Screen Shot 2019-05-11 at 2 53 35 PM" src="https://user-images.githubusercontent.com/9334646/57569938-ac3ad380-73fc-11e9-9e47-0d542c338535.png">

Please check the README.MD for the full reference of the mockup.

## Expected Behavior

Sign up section has been added to the Causes index page similarly as the artists.

## Current Behavior

No current behavior.

**Comment by yakryder** [comment]
> <img alt="Screen Shot 2019-05-11 at 2 53 35 PM" width="710" src="https://user-images.githubusercontent.com/9334646/57569938-ac3ad380-73fc-11e9-9e47-0d542c338535.png">

One native English speaker's opinion:
Sign up section should read "You can make a difference today!" (no capital letter 'M', 'a' instead of 'the')

**Comment by javpet** [comment]
Thanks @SherSpock! This what we received with the mockups, we'll make the change when we implement this component.

**Comment by yakryder** [comment]
Great!
