### ISSUE TITLE
Add node-version

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#24]
Add `.node-version` file for nvm automatic switching when cd-ing into project directory.
 
Unfortunately, in vs code's integrated terminal, you have to `cd ..` and cd back in.
 
In Mac's Terminal it works automatically.

File just needs: 
```
v10.13.0
```
Need to run these commands on local computer:
```
yarn global add  avn avn-nvm avn-n
avn setup
```
Please add these commands to environment setup section.

https://github.com/wbyoung/avn

**Comment by aonomike** [comment]
@FedericoEsparza I was testing this with fish and it wasnt successful, I have found this link to help the fishermen https://github.com/martinkacmar/fish-avn
