### ISSUE TITLE
Update cursor css property

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#254]
Update cursor css property

Many links are missing the cursor css property set to pointer.

![pointer](https://static.thenounproject.com/png/126284-200.png)

Run and scan the css and app to add the property and value to the links/buttons.

**Comment by javpet** [comment]
Thanks for this ticket @FedericoEsparza! Some of the buttons are missing the cursor pointer because we were unsure about the functionality or logic. But we can review of course!
