### ISSUE TITLE
Adding additional routes

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#31]
From the mockup as I see the following routes might be beneficial:

- home "/"
- about "/about" // rendering about page
- causes "/causes" // rendering list of causes
- artists "/artists" // rendering list of artists
- artist "/artists/:id" ✔️
- artist edit "/artistst/:id/edit" // editing existing artist (update, delete) 
- artist create "/artists/new" // creating new artist
- performances "/performances" // rendering performances list
- contact "/contact" // rendering a contact page

Is this fine @FedericoEsparza to start with?

**Comment by FedericoEsparza** [comment]
@javpet Yes, Peter. That's perfect! Thanks for writing that up.
