### ISSUE TITLE
Make header sticky on scrolling in both mobile and desktop view

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#360]
When a user scrolls down on the page, he should be able to see the page header at all 
times. 

## Expected Behavior

The header on the page stays sticky while scrolling
## Current Behavior

The header scrolls up with the page as we scroll
## Possible Solution

Make the header fixed

**Comment by bautistaaa** [comment]
https://github.com/AgileVentures/sfn-client/pull/410

**Comment by javpet** [comment]
Fixed.
