### ISSUE TITLE
Adding typography fundamentals

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#37]
As following the Tachyons library structure, I would like to add a clear hierarchical typography scale to the project that will help developers and designers working together in the system.

**Comment by FedericoEsparza** [comment]
@javpet I would like to empower you to do that, Peter. 😁

**Comment by javpet** [comment]
Sure, I'll pick this up next week along with setting the colors too.

**Comment by javpet** [comment]
PR has been created: https://github.com/AgileVentures/sfn-client/pull/40
