### ISSUE TITLE
Add end date on the cause description 

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#395]
Add Cause end date in the cause description in the cause page
## Expected Behavior

An end date of the cause should be added with the description in the cause's page
## Current Behavior

The end date of the cause has not been added
## Possible Solution

See image below
<img width="319" alt="Screen Shot 2019-09-19 at 6 40 01 PM" src="https://user-images.githubusercontent.com/1543546/65259822-fa2fb880-db0d-11e9-93d9-799c3dfbe520.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by javpet** [comment]
I'm wondering if for this purpose which approach is better:
- Showing the end date in a date format
OR
- Showing how many days remained in days format as we do it in the donations part

**Comment by aonomike** [comment]
I think days remaining is better @javpet
