### ISSUE TITLE
Adding a loader component

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#408]
We need a component which presents a loader as a form of notification for the user about the progress that's happening.

## Expected Behavior

A loader component is added to the shared components.

## Current Behavior

We're mostly only using the "Loading..." text for these use cases.

**Comment by bautistaaa** [comment]
https://github.com/AgileVentures/sfn-client/pull/409

**Comment by javpet** [comment]
@bautistaaa great contribution, thanks!
