### ISSUE TITLE
About page is not responsive

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#418]
About page on mobile looks pretty bad, let's make it responsive like the other pages

<img width="187" alt="Screen Shot 2019-10-12 at 8 50 51 PM" src="https://user-images.githubusercontent.com/9334646/66706382-0fc18800-ed32-11e9-9822-3ad81fc9de72.png">

## Expected Behavior

About page works responsively like the other pages.

## Current Behavior

About page text looks bad and unreadable.

**Comment by PabloPap** [comment]
Hello @javpet . Can I work on this issue?

**Comment by javpet** [comment]
Sure @PabloPap! Bring it on! Let us know if you need any guidance! As you will see in the codebase we're using utility classes for spacing and so, please use those instead of hardcoded values like `margin-top: $margin-r` instead of `margin-top: 16px`

**Comment by javpet** [comment]
Hey @PabloPap! How is it going? Do you need any extra help with the issue?

**Comment by PabloPap** [comment]
Hello @javpet. I had an issue with the google authentication - the project was crashing , but i solved it (probably browser extensions created the issue, moved on a clean browser).

**Comment by javpet** [comment]
Great, no worries! We've made a couple of changes in the meantime, just always make sure before you push, you pull from the upstream repo. 🙂

**Comment by PabloPap** [comment]
Hi @javpet . It seems i don't have access to the repo(?)
"Permission to AgileVentures/sfn-client.git denied to PabloPap.
fatal: unable to access 'https://github.com/AgileVentures/sfn-client/': The requested URL returned error: 403"

**Comment by javpet** [comment]
@aonomike can you please help?

**Comment by aonomike** [comment]
Hi @PabloPap I have added you as a collaborator to the repo. You should have received an invite message. Kindly reach out in case of anything.

**Comment by PabloPap** [comment]
@aonomike still no luck. I look it up and some people mention that it is a ssh problem, but none of the solutions worked for me. 
The complete process:
git push --set-upstream upstream about-page-responsive
remote: Permission to AgileVentures/sfn-client.git denied to PabloPap.
fatal: unable to access 'https://github.com/AgileVentures/sfn-client/': The requested URL returned error: 403
