### ISSUE TITLE
Contact page not responsive

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#419]
The contact page is not responsive. :/ 

![Screen Shot 2019-10-12 at 8 52 25 PM](https://user-images.githubusercontent.com/9334646/66706400-4bf4e880-ed32-11e9-9733-072e8ee508b6.png)

## Expected Behavior

Contact page is responsive.

## Current Behavior

Currently the information is crammed.

**Comment by Shahmahdi** [comment]
Hello, I want to work on this issue. Can you assign me on this issue @javpet

**Comment by javpet** [comment]
Absolutely! Please reach us if something is not clear or you need some more guidance. 🙂

**Comment by aonomike** [comment]
@Shahmahdi you can join our slack channel by registering through [Agileventures](https://www.agileventures.org/) feel free to reach out in case you have any trouble :)

**Comment by javpet** [comment]
Fixed by PR from @Shahmahdi
