### ISSUE TITLE
Link Performances page to the backend

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#431]
Currently the performances displayed on the performance page are hardcoded, they should be implemented to get data from the backend

## Expected Behavior

Performances are fetched from the backend
## Current Behavior

Performances are hard coded

**Comment by javpet** [comment]
@aonomike is this something I can do similarly how we did for the causes, or is there something needs to be changed on the backend for it?

**Comment by aonomike** [comment]
Hi @javpet yeah...I only noticed that I need to improve the performences query from the backend, but what we have is qood for a start

**Comment by javpet** [comment]
Thanks Mike! So this means if I copy the way we are querying the causes, I can implement the performances? 🤕

**Comment by aonomike** [comment]
Yep, I think you should always test your queries on graphiql to see if they run. But essentially yes, a mirror of causes can work for performances.

**Comment by javpet** [comment]
Fixes with previous PR.
