### ISSUE TITLE
Fix Cause Card progress bar for percentages greater than 100%

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#441]
The cause card progress bar overflows for percentages greater than 100%. We may need to figure out how to handle percentages above 100%
## Expected Behavior

Fix the overflow of the causes card for percentages over 100%
## Current Behavior

The causes card progress bar overflows for percentages over 100
## Possible Solution

Some css styling and design thinking maybe?
## Steps to Reproduce (for bugs)

1. In the backend create a cause with the value of donations greater than 100% e.g target Amount 1000 donatedAmount: 100000
2. See in the trending `/causes` route  that it overflows

<img width="1314" alt="Screen Shot 2019-11-14 at 8 11 27 PM" src="https://user-images.githubusercontent.com/1543546/68880274-0013d580-071c-11ea-91a0-334d63d1471b.png">

**Comment by javpet** [comment]
Fixed in an earlier PR.
