### ISSUE TITLE
Adding newsletter sign up page // modal?

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#461]
We need a page where users could sign up to our newsletter OR We might need to modify the shared banner component to receive email inputs

@aonomike we need to modify the user schema as well to have a boolean within the model to receive newsletter or not, by default we can set this one to false

## Expected Behavior

Have a newsletter sign up page OR modified the banner component to receive newsletter sign ups

**Comment by aonomike** [comment]
Great idea @javpet I am thinking just a boolean field on registration for users to accept receiving news letters. Also just a textbox in the banner would be great...not sure how you love the use of modals? what do you think @azure-may

**Comment by javpet** [comment]
I close this ticket, as a new ticket has been created for the backend to add this boolean value for newsletter sign ups.
