### ISSUE TITLE
Create mobile navigation based on desktop one

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#54]
The mockups have been created as a desktop, but eventually we'll need a mobile version of the site, and it's good to do it parallel. Does Agile Ventures have some icon library you use already, maybe @FedericoEsparza you know? I would suggest the [Noun project](https://thenounproject.com/) as they have really nice icons.

**Comment by javpet** [comment]
As searching a little I also found that Font Awesome has a quite handy React implementation in place as well: https://fontawesome.com/how-to-use/on-the-web/using-with/react

**Comment by FedericoEsparza** [comment]
@javpet We've used Font Awesome a fair bit at AV, and we used it in the `championer_one` project for the social media icons. We can use it, since it has a free open-source tier.

We'll want to use https://github.com/FortAwesome/react-fontawesome

With noun project, it appears that we'd have to provide attribution, or upgrade.

**Comment by javpet** [comment]
I was asking since at some point we might need them, but at first I'll try to avoid them and use elements + labels combo. 😇

**Comment by jmpainter** [comment]
Are there any preferred setups for the design and implementation of a responsive nav bar? There are some components available, or we could create our own

**Comment by jmpainter** [comment]
It seems like a responsive navbar component would have to contain the state of whether it was open or closed or not. It looks like there is a convention of putting stateful components in /containers and functional components in /components - would you want to move the Header component to /containers and keep the navbar state there?

**Comment by FedericoEsparza** [comment]
@jmpainter Could you potentially create an `src/containers/Layout/Layout.js` container, instead, and pass in "state" to the Header and Footer components, via props?

If you think you can do that, please also move the Header and Footer component folders into an `src/components/Layout/` folder.

**Comment by jmpainter** [comment]
Yes, that sounds good, I'll go with that

**Comment by jmpainter** [comment]
So, if, the Layout container would contain the Header and Footer components, should there be a separate container for routes that would also be contained in the Layout container?

**Comment by jmpainter** [comment]
Ok, forget that question - I see how this can work. I'll have a PR for this soon.

**Comment by FedericoEsparza** [comment]
Sorry, Josh. I just saw the original question from Saturday. I am a bit confused by it, so I’ll take your direction and forget it. 😁
