### ISSUE TITLE
Add performance components to ArtistContainer

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#56]

**Comment by FedericoEsparza** [comment]
Please add the Performance components by importing them into the `ArtistContainer` and nesting them inside an `ArtistPerformanceList` component (the red rectangle below).
 
Name them `ArtistPerformance`, as referenced in ticket #57 (cyan rectangles below)

Later, when we insert the performance data dynamically, through props, we'll probably refactor and reorganize them in separate files.

You'll probably need to put `{props.children}`inside the return div of the `ArtistPerformanceList` component file.
![Screenshot 2019-02-10 10.22.31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e387b76082a50f00d31003/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416753e7854e37a20cbb17af1112a43434d0eee1e020a17b8eb8339a3e53f718b5c59ebd9385f75c43f11aebd851cbf01bf21da5d99a4fedb1294b7607caddecd5d340c041083fe5831a9914ace50f748e24a50b65e.png)

**Comment by javpet** [comment]
Hopefully we understood correctly, we created the the PR for it https://github.com/AgileVentures/sfn-client/pull/69

**Comment by javpet** [comment]
@FedericoEsparza we kinda afraid to merge this in without your permission. :)

**Comment by FedericoEsparza** [comment]
@javpet I’m reviewing right now. One sec.
