### ISSUE TITLE
Add Waffle banner-link to README

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#62]
Add Waffle banner-link to README

Just add the following code to the top of the README file:
```
[![Waffle.io - Columns and their card count](https://badge.waffle.io/AgileVentures/sfn-client.svg?columns=all)](https://waffle.io/AgileVentures/sfn-client)
```

It's a convenient link to the Waffle board, from the github repo.

**Comment by javpet** [comment]
Fixes https://github.com/AgileVentures/sfn-client/pull/68
