### ISSUE TITLE
Dockerize sfn-client

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#65]
Implement docker setup for development

**Comment by FedericoEsparza** [comment]
@aonomike Let's focus on dockerizing for **_deployment_** first.

**Comment by daumie** [comment]
Once we have the server up and ensure it's working properly.
I can pair with anyone willing to pick this issue

**Comment by FedericoEsparza** [comment]
@75pollet is assigned to it. Thanks for offering to pair, Dominic. 
I'd appreciate it if you and her, at least (@mattwr18 too, if he's interested), could schedule a pairing session.

@Kachulio1  @LindaKadz Any progress on [Standup GCP VMs for singforneeds #6](https://github.com/AgileVentures/PhoenixOne/issues/6) ?

**Comment by yakryder** [comment]
^ I'd be interested in looking at this too if I'm available during that session. I don't have a lot of Docker experience and this seems like it would be one of the simpler dockerizations.

**Comment by FedericoEsparza** [comment]
👌🏽

**Comment by daumie** [comment]
@SherSpock , @75pollet  I would  like to know if you guys  got time so we can review together my version of implementing this  task.

**Comment by yakryder** [comment]
@daumie Yep posting on #65
