### ISSUE TITLE
Add coveralls

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#70]
Add coverrals for test coverage

**Comment by FedericoEsparza** [comment]
https://coveralls.io/

**Comment by aonomike** [comment]
We need to do a github signup for coverrals and add agileventures to coverrals. Maybe something you can help with this one @FedericoEsparza

**Comment by FedericoEsparza** [comment]
I added more admins to the repo, last week.
So I removed my assignment to this ticket, in case the weekend crew wants to get it done.
