### ISSUE TITLE
Add Enzyme adapter setup

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#82]
Add Enzyme adapter setup

So that we don't have to add enzyme adapter configuration to every test file, we need to create a common test setup file:
```
src/setupTests.js
```

You'll add the following code into that file:
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```
See https://airbnb.io/enzyme/docs/installation/ for more guidance

**Comment by javpet** [comment]
Fixes https://github.com/AgileVentures/sfn-client/pull/91
