### ISSUE TITLE
Refactor Causes Container

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#85]
Refactor Causes Container

After #83 has been merged in, refactor, move, and rename `src/components/Causes/CausesContainer.js`.

It's new home and name will be `src/components/Causes/Causes.js`

Move the test along with it: `src/components/Causes/Causes.test.js`
will now be at `src/containers/Causes/Causes.test.js`

You'll need to refactor the reference to `./CausesContainer` and change it to `./Causes`
in the test file.

You'll also need to refactor the class name and the export default to `Causes`

In `src/components/App.js` you'll have to refactor the import statement to 
```
import Causes from "../containers/Causes/Causes";
```
And you'll also have to refactor the reference to the container in that file from `{CausesContainer}` to `{Causes}`

Leave an empty `.keep` file in `src/components/Causes/`

**Comment by aonomike** [comment]
Hi @FedericoEsparza what's the reason behind leaving the .keep in `src/components/Causes/` ? why not just delete it? some kind of #YAGNI...

**Comment by FedericoEsparza** [comment]
@aonomike  I think you can safely delete it. I forgot why I thought it was necessary.
