### ISSUE TITLE
Add how to review a PR documentation

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#86]
Add how to review a PR documentation

I want to empower the team to review and merge each other's tickets, so that in a weekend, you're not waiting on me to review an merge a ticket that is blocking other PRs.

This will also keep more of the team aware of a wider breadth of the codebase.

**Except for documentation PRs, it's important to run the app locally, because many times, you'll find inadvertent behavior that the CI tests won't catch.**

As a huge head start you can copy much of this document, written largely by @mattwr18, in one of his greatest PRs ever. 😁 https://github.com/championer-org/championer_one/blob/develop/devdocs/HOW-TO-REVIEW-A-DEVELOP-PR.md

That is obviously a Phoenix app that uses npm, so a lot of it will need to be altered, but here are the tl;dr commands for us:

```js
git fetch upstream
git checkout 57-artist-performance-component //for example
yarn
yarn test
// Press a to run all tests
// Press q to quit watch mode.
yarn start
// Review and inspect the app and its elements for expected and unexpected behavior
```

Also add instructions that you always want to review the **Files changed.**

You can navigate there by clicking on the tab in the PR page:

<img width="589" alt="screenshot 2019-02-17 08 33 03" src="https://user-images.githubusercontent.com/11988089/52914523-5523d780-32c1-11e9-9564-cf51bab924a6.png">

...or adding `/files` to the end of the PR url, for example `https://github.com/AgileVentures/sfn-client/pull/71/files`

**I prefer to view the diffs in _Unified_** form, rather than the default _Split_.

<img width="578" alt="screenshot 2019-02-17 08 37 59" src="https://user-images.githubusercontent.com/11988089/52914564-e430ef80-32c1-11e9-81ce-99142cd222a6.png">

You can also add comments to a particular line of code, by clicking on the plus icon when you hover over a line:

<img width="556" alt="screenshot 2019-02-17 08 43 51" src="https://user-images.githubusercontent.com/11988089/52914657-08410080-32c3-11e9-9a0f-b73a891acf44.png">

You can then either just provide the single comment or start a review, if you haven't, yet:

<img width="792" alt="screenshot 2019-02-17 08 44 40" src="https://user-images.githubusercontent.com/11988089/52914665-2444a200-32c3-11e9-95d3-113a56dc4884.png">

**Comment by aonomike** [comment]
There are some tips here as well :)
https://medium.com/@muthuks/here-is-the-checklist-for-reviewing-your-own-react-code-17c03761ac38
