### ISSUE TITLE
Research react chart libraries

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/sfn-client#89]
Research react chart libraries

There's new ones being created all the time.

There's probably an awesome one that we haven't heard of.

Let's find and use that one for our charts.

Just report the possibilities.

Feel free to create a branch and test them out in our MoneyRaised component.

**Comment by javpet** [comment]
Obviously the most known library is D3 (I'm going to learn it in April actually), but I've collected some other less known ones:

- https://frappe.io/charts
- https://github.com/tannerlinsley/react-charts
- https://www.chartjs.org/
- http://recharts.org/en-US/

**Comment by FedericoEsparza** [comment]
@javpet Good research. Thanks!
We can go with D3, since you'll be learning it anyway.

Have you had a chance to create a branch and explore the other ones? If so, any further thoughts about them?

**Comment by javpet** [comment]
I didn't have a chance to check the others @FedericoEsparza but from developer communities I heard good experiences of https://www.chartjs.org/ since it's really simple, so I'm wondering D3 might be an overkill for our case.

**Comment by javpet** [comment]
Just came across this one, seems crazy simple as well: https://quickchart.io/

**Comment by FedericoEsparza** [comment]
Cool. Thanks for linking. I’m happy to go with whichever library the team or ticket implementer is most motivated to use, even if it is overkill. If there’s still a decision to be made, after the research implementation, then I’ll chime in.

**Comment by aonomike** [comment]
We are using https://nivo.rocks 
Was voted since it seamlessly works with react and has some touch of d3 it :)
